micronaut:
  application:
    name: server
  server:
    cors:
      enabled: true
netty:
  default:
    allocator:
      max-order: 3
userdb:
  name: 'paylent'
  collection: 'user'
paymentdb:
  name: 'paylent'
  collection: 'payment'

mongodb.uri: mongodb://root:rootpassword@${MONGO_HOST:mongo}:${MONGO_PORT:27017}/mydb
